version: '3'

services:
  react-app:
    build:
     context: .
     dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
     - '3000:3000'
    volumes:
     - type: bind
       source: ./
       target: /app
     - /app/node_modules
      
    environment:
     - WATCHPACK_POLLING=true


    command: sh -c "npm run dev"


  nginx:
    image: nginx
   # build:
   #  context: .
   #  dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
     - '80:80'
     - '443:443'
    volumes:
     - type: bind
       source: ./build
       target:  /usr/share/nginx/html
      