version: '3'

services:
  react-app:
    build:
     context: .
     dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
     - '80:3000'
    volumes:
      - ./src:/app:rw
  #   - type: bind
  #     source: ./src
  #     target: /app
     #- ./src:/app
    environment:
      - CHOKIDAR_USEPOLLING=true


    command: sh -c "cd dorian-blog && npm start"
#    env_file:
#     - ./.env.local