version: '3'

services:
  react-app:
    build:
     context: .
     dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
     - '3000:3000'
    volumes:
     - type: bind
       source: ./
       target: /app
     - /app/node_modules
      
    environment:
     - WATCHPACK_POLLING=true


    command: sh -c "npm run dev"
    #command: sh -c "npm start"
    #command: sh -c "
    #  npm build &&
    #  npm start"
#    env_file:
#     - ./.env.local