version: '3'

services:
  react-app:
    build:
     context: .
     dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
     - '3000:3000'
    volumes:
     - type: bind
       source: ./
       target: /app
     - /app/node_modules
      
    environment:
      - CHOKIDAR_USEPOLLING=true


    command: sh -c "npm start"
    #command: sh -c "cd dorian-blog && npm start"
#    env_file:
#     - ./.env.local